config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :user_stocks, except: [:show, :edit, :update]

  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stocks', to: 'stocks#search'

end

app/models/stock.rb
class Stock < ActiveRecord::Base

  has_many :user_stocks
  has_many :users, through: :user_stocks

  # class level method
  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

  def self.new_from_lookup(ticker_symbol)
    looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
    return nil unless looked_up_stock.name

    new_stock = new(ticker: looked_up_stock.symbol, name: looked_up_stock.name)
    new_stock.last_price = new_stock.price
    new_stock
  end

  def price
    closing_price = StockQuote::Stock.quote(ticker).close
      return "#{closing_price} (Closing)" if closing_price

    opening_price = StockQuote::Stock.quote(ticker).open
      return "#{opening_price} (Opening)" if opening_price
        "Unavailable"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks

  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

  def under_stock_limit?
    (user_stocks.count < 10)
  end

  def stock_already_added?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end

end

app/models/user_stock.rb
class UserStock < ActiveRecord::Base
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock]
      @stock = Stock.find_by_ticker(params[:stock])
      @stock ||= Stock.new_from_lookup(params[:stock])
    end

    if @stock
      # render json: @stock # for testing.. display value(s)
      render partial: 'lookup'
    else
      render status: :not_found, nothing: true
    end

  end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  before_action :set_user_stock, only: [:show, :edit, :update, :destroy]

  # GET /user_stocks
  # GET /user_stocks.json
  def index
    @user_stocks = UserStock.all
  end

  # GET /user_stocks/1
  # GET /user_stocks/1.json
  def show
  end

  # GET /user_stocks/new
  def new
    @user_stock = UserStock.new
  end

  # GET /user_stocks/1/edit
  def edit
  end

  # POST /user_stocks
  # POST /user_stocks.json
  def create
    if params[:stock_id].present?
      @user_stock = UserStock.new(stock_id: params[:stock_id], user: current_user)
    else
      stock = Stock.find_by_ticker(params[:stock_ticker])
      if stock
        @user_stock = UserStock.new(user: current_user, stock: stock)
      else
        stock = Stock.new_from_lookup(params[:stock_ticker])

        if stock.save
          @user_stock = UserStock.new(user: current_user, stock: stock)
        else
          @user_stock = nil
          flash[:error] = "Stock is not available"
        end
      end
    end

    respond_to do |format|
      if @user_stock.save
        format.html { redirect_to my_portfolio_path, notice: "Stock #{@user_stock.stock.ticker} was successfully added" }
        format.json { render :show, status: :created, location: @user_stock }
      else
        format.html { render :new }
        format.json { render json: @user_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_stocks/1
  # PATCH/PUT /user_stocks/1.json
  def update
    respond_to do |format|
      if @user_stock.update(user_stock_params)
        format.html { redirect_to @user_stock, notice: 'User stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_stock }
      else
        format.html { render :edit }
        format.json { render json: @user_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_stocks/1
  # DELETE /user_stocks/1.json
  def destroy
    @user_stock.destroy
    respond_to do |format|
      format.html { redirect_to user_stocks_url, notice: 'User stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_stock
      @user_stock = UserStock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_stock_params
      params.require(:user_stock).permit(:user_id, :stock_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_spinner.html.erb
<div id="spinner" class="row col-md-12 text-center spinner" style="display: none;">
  <i class='fa fa-spinner fa-spin fa-3x'></i>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FinanceTracker" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">FinanceTracker</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/stocks/_lookup.html.erb
<div id="stock-lookup">
  <h3>Search for Stocks</h3>
    <%= form_tag search_stocks_path, remote: true, method: :get, id: 'stock-lookup-form' do %> <!-- we will use AJAX here.. -->
      <div class="form-group row no-padding text-center col-md-12">
        <div class="col-md-10">
          <%= text_field_tag :stock, params[:stock], placeholder: 'Stock Ticker Symbol', autofocus: true, class: 'form-control search-box input-lg' %>
        </div>
        <div class="col-md-2">
          <%= button_tag(type: :submit, class: 'btn btn-lg btn-success') do %>
            <i class='fa fa-search'></i> Look up a stock
          <% end %>
        </div>
      </div>
    <% end %>

    <%= render 'common/spinner' %>

    <% if @stock %>
      <div id="stock-lookup-results" class="well results-block">
        <strong>Symbol:</strong> <%= @stock.ticker %>
        <strong>Name:</strong> <%= @stock.name %>
        <strong>Price:</strong> <%= @stock.price %>

        <% if current_user.can_add_stock?(@stock.ticker) %>
          <%= link_to "Add to my Stocks", user_stocks_path(user: current_user, stock_ticker:@stock.ticker, stock_id: @stock_id ? @stock.id: ''), class: 'btn btn-xs btn-success', method: :post %>
        <% else %>
          <span class="label label-default">
            Stock cannot be added because you have already added
              <% if !current_user.under_stock_limit? %>
                10 stocks
              <% end %>

              <% if current_user.stock_already_added?(@stock.ticker) %>
                this stock
              <% end %>
          </span>
        <% end %>



      </div>
   <% end %>

  <div id="stock-lookup-errors"></div>

</div>

app/views/user_stocks/_form.html.erb
<%= form_for(@user_stock) do |f| %>
  <% if @user_stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_stock.errors.count, "error") %> prohibited this user_stock from being saved:</h2>

      <ul>
      <% @user_stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :stock_id %><br>
    <%= f.number_field :stock_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_stocks/edit.html.erb
<h1>Editing User Stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_stock %> |
<%= link_to 'Back', user_stocks_path %>

app/views/user_stocks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Stocks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_stocks.each do |user_stock| %>
      <tr>
        <td><%= user_stock.user_id %></td>
        <td><%= user_stock.stock_id %></td>
        <td><%= link_to 'Show', user_stock %></td>
        <td><%= link_to 'Edit', edit_user_stock_path(user_stock) %></td>
        <td><%= link_to 'Destroy', user_stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User stock', new_user_stock_path %>

app/views/user_stocks/new.html.erb
<h1>New User Stock</h1>

<%= render 'form' %>

<%= link_to 'Back', user_stocks_path %>

app/views/user_stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_stock.user_id %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @user_stock.stock_id %>
</p>

<%= link_to 'Edit', edit_user_stock_path(@user_stock) %> |
<%= link_to 'Back', user_stocks_path %>

app/views/users/my_portfolio.html.erb
<%= render 'stocks/lookup' %>

app/views/welcome/index.html.erb
 <h1>Welcome to the homepage of the finance tracker app</h1>
 <%= link_to 'logout', destroy_user_session_path, method: :delete %>